Repository ohtuprojekti-Kierratysavustin/Kierratysavustin, pull requests merged in 2021-12, with the labels that each got.

#160 Recycle locations improving #156
  client/src/App.tsx
  client/src/components/Map.tsx
  client/src/components/MaterialsCheckboxGroup.tsx
  client/src/components/views/RecycleLocationsView.tsx
  client/src/services/credentials.tsx
  client/src/store.ts
  client/src/styles.css
  client/src/tests/RecycleLocationsView.test.tsx
  client/src/tests/testdata/recycleLocations.js
  client/src/types/objects.ts
  documents/teknologiat.md
Labels: enhancement

#159 Yksittaisen tuotteen kierratysstatistiikka 155
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ProductsList.tsx
  client/src/components/RecycleGraph.tsx
  client/src/components/forms/LoginForm.tsx
  client/src/components/forms/ProductUserCountForm.tsx
  client/src/components/forms/RecycleGraphForm.tsx
  client/src/components/views/ProductView.tsx
  client/src/components/views/RecycleStatisticsView.tsx
  client/src/services/counters.ts
  client/src/services/productUserCount.ts
  client/src/services/products.ts
  client/src/services/statistics.ts
  client/src/store.ts
  client/src/styles.css
  client/src/tests/ProductUserCountForm.test.tsx
  client/src/tests/ProductView.test.js
  client/src/tests/ProductView.test.tsx
  client/src/types/objects.ts
  server/app.js
  server/controllers/counters.js
  server/controllers/productUserCounter.js
  server/controllers/statistics.js
  server/requests/product_user_count.rest
  server/requests/purchase.rest
  server/requests/recycle.rest
  server/requests/user_product_recyclingrates_per_day.rest
  server/requests/user_product_recyclingrates_per_product.rest
  server/tests/product_user_counter.test.js
  server/tests/statistics.test.js
  server/tests/test_helper.js
Labels: enhancement

#164 Fix product list horizontal scroll on mobile view
  client/src/components/ProductsList.tsx
  client/src/components/forms/FavoritesForm.tsx
  client/src/components/views/ProductView.tsx
  client/src/styles.css
Labels: Priority High

#169 Code cleanup for client
  client/src/components/FileInput.tsx
  client/src/components/InfoBar.tsx
  client/src/components/Map.tsx
  client/src/components/NavigationBar.tsx
  client/src/components/Notification.tsx
  client/src/components/ProductsList.tsx
  client/src/components/RecycleGraph.tsx
  client/src/components/forms/InstructionForm.tsx
  client/src/components/forms/LoginForm.tsx
  client/src/components/forms/ProductUserCountForm.tsx
  client/src/components/forms/RecycleGraphForm.tsx
  client/src/components/forms/RegisterForm.tsx
  client/src/components/forms/VoteForm.tsx
  client/src/components/views/FrontPage.tsx
  client/src/components/views/ProductListView.tsx
  client/src/components/views/ProductView.tsx
  client/src/components/views/RecycleStatisticsView.tsx
  client/src/tests/FavoritesForm.test.js
  client/src/tests/FrontPage.test.js
  client/src/tests/InstructionForm.test.js
  client/src/tests/ProductListView.test.js
  client/src/tests/ProductUserCountForm.test.tsx
  client/src/tests/ProductView.test.tsx
  client/src/tests/ProductsList.test.js
  client/src/tests/RecycleLocationsView.test.tsx
  client/src/tests/RegisterForm.test.tsx
  client/src/tests/VoteForm.test.tsx
Labels: refactor
