Repository ohtuprojekti-Kierratysavustin/Kierratysavustin, pull requests merged in 2021-09, with the labels that each got.

#105 Autentikoinnin refaktorointi
  client/package-lock.json
  client/package.json
  e2e_tests/package-lock.json
  e2e_tests/package.json
  server/controllers/products.js
  server/controllers/users.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/utils/auth.js
  server/utils/config.js
Labels: refactor

#106 Refactor client to TypeScript
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/FavoritesForm.tsx
  client/src/components/FavouriteProducts.tsx
  client/src/components/FrontPage.tsx
  client/src/components/InfoBar.tsx
  client/src/components/InstructionForm.tsx
  client/src/components/LoginForm.tsx
  client/src/components/NavigationBar.tsx
  client/src/components/Notification.tsx
  client/src/components/Product.tsx
  client/src/components/ProductForm.tsx
  client/src/components/ProductList.tsx
  client/src/components/RegisterForm.tsx
  client/src/components/SearchBarForm.tsx
  client/src/components/VoteForm.tsx
  client/src/react-app-env.d.ts
  client/src/services/products.ts
  client/src/services/token.ts
  client/src/services/user.ts
  client/src/store.js
  client/src/store.ts
  client/src/tests/Product.test.js
  client/src/types.ts
  client/tsconfig.json
Labels: refactor

#110 Tuotteiden poistaminen 100
  client/src/components/DeleteProduct.tsx
  client/src/components/Product.tsx
  client/src/components/ProductList.tsx
  client/src/services/products.ts
  client/src/types.ts
  documents/kuvat/tuotteen-poistaminen.png
  e2e_tests/cypress/integration/recycling-app.spec.js
  server/controllers/products.js
  server/models/product.js
  server/requests/delete_product.rest
  server/tests/kierratysavustin_api.test.js
  server/tests/test_helper.js
Labels: enhancement, Priority Medium

#112 [WIP] Kotitalouden kierratysaste mvp 104
  client/src/components/FavoritesForm.tsx
  client/src/components/FavouriteProducts.tsx
  client/src/components/Product.tsx
  client/src/components/ProductList.tsx
  client/src/components/RecycleForm.tsx
  client/src/services/recycle.ts
  client/src/services/token.ts
  client/src/styles.css
  client/src/tests/RecycleForm.test.tsx
  documents/kayttoohje.md
  documents/kuvat/recycleCount.png
  server/app.js
  server/controllers/productUserRecycleCount.js
  server/controllers/products.js
  server/controllers/tests.js
  server/controllers/users.js
  server/models/productUserRecycleCount.js
  server/models/user.js
  server/requests/product_recycle_count.rest
  server/requests/recycle.rest
  server/tests/kierratysavustin_api.test.js
  server/tests/test_helper.js
  server/utils/auth.js
Labels: Priority Medium
