Repository ohtuprojekti-Kierratysavustin/Kierratysavustin, pull requests merged in 2021-11, with the labels that each got.

#142 RegisterForm refaktorointia ja pari testiä
  client/src/App.tsx
  client/src/components/ProductsList.tsx
  client/src/components/forms/DeleteInstructionForm.tsx
  client/src/components/forms/DeleteProduct.tsx
  client/src/components/forms/FavoritesForm.tsx
  client/src/components/forms/InstructionForm.tsx
  client/src/components/forms/LoginForm.tsx
  client/src/components/forms/ProductForm.tsx
  client/src/components/forms/ProductUserCountForm.tsx
  client/src/components/forms/RegisterForm.tsx
  client/src/components/forms/VoteForm.tsx
  client/src/components/views/ProductView.tsx
  client/src/services/productUserCount.ts
  client/src/services/user.ts
  client/src/tests/ProductUserCountForm.test.tsx
  client/src/tests/README.md
  client/src/tests/RegisterForm.test.js
  client/src/tests/RegisterForm.test.tsx
  client/src/types/requestResponses.ts
  server/controllers/login.js
  server/tests/test_helper.js
Labels: bugfix

#145 Image upload (product view)
  client/package-lock.json
  client/package.json
  client/src/components/ProductsList.tsx
  client/src/components/UploadImage.tsx
  client/src/components/forms/ProductForm.tsx
  client/src/components/views/ProductListView.tsx
  client/src/components/views/ProductView.tsx
  client/src/components/views/RecycleStatisticsView.tsx
  client/src/services/files.ts
  client/src/services/products.ts
  client/src/styles.css
  client/src/types/objects.ts
  e2e_tests/package-lock.json
  package-lock.json
  server/app.js
  server/controllers/file.js
  server/models/product.js
  server/package-lock.json
  server/package.json
  server/requests/get_image.rest
Labels: enhancement, Priority High

#146 Image upload (product form)
  client/src/components/FileInput.tsx
  client/src/components/UploadImage.tsx
  client/src/components/forms/ProductForm.tsx
  server/package.json
Labels: enhancement, Priority High

#144 Kuvaajalle oma komponentti
  client/src/components/RecycleGraph.tsx
  client/src/components/views/RecycleStatisticsView.tsx
Labels: refactor

#147 Suosikkeihin lisaaminen refactorointi
  client/package-lock.json
  client/src/App.tsx
  client/src/components/UploadImage.tsx
  client/src/components/forms/DeleteInstructionForm.tsx
  client/src/components/forms/DeleteProduct.tsx
  client/src/components/forms/LoginForm.tsx
  client/src/services/products.ts
  client/src/tests/ProductUserCountForm.test.tsx
  client/src/tests/RecycleStatisticsView.test.tsx
  client/src/types/objects.ts
  documents/Backend-dokumentaatio.md
  documents/kuvat/db-20211108.png
  documents/tietokanta/Kierrätysavustin_tietokanta.drawio
  e2e_tests/package-lock.json
  server/controllers/file.js
  server/controllers/productUserCounter.js
  server/controllers/products.js
  server/controllers/users.js
  server/error/exceptions.js
  server/models/instruction.js
  server/models/product.js
  server/models/user.js
  server/package-lock.json
  server/tests/kierratysavustin_api.test.js
  server/tests/product_user_counter.test.js
  server/tests/test_helper.js
Labels: Priority Low, refactor

#154 Recycle locations
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/Map.tsx
  client/src/components/NavigationBar.tsx
  client/src/components/RecycleGraph.tsx
  client/src/components/views/RecycleLocationsView.tsx
  client/src/services/credentials.tsx
  client/src/services/kierratysInfo.ts
  client/src/styles.css
  client/src/tests/ProductUserCountForm.test.tsx
  client/src/tests/RecycleLocationsView.test.tsx
  client/src/tests/RegisterForm.test.tsx
  client/src/tests/testdata/recycleLocations.js
  client/src/types/objects.ts
  documents/kayttoohje.md
  documents/kuvat/kierratyspisteet.png
  package-lock.json
  package.json
  server/.gitignore
  server/app.js
  server/controllers/credentials.js
  server/utils/config.js
Labels: enhancement

#153 Kaytto oikeus roolit 141
  client/src/components/forms/DeleteInstructionForm.tsx
  client/src/enums/roles.ts
  client/src/tests/README.md
  client/src/types/objects.ts
  client/src/utils/roles.ts
  documents/arkkitehtuurista.md
  server/app.js
  server/controllers/admin.js
  server/controllers/login.js
  server/controllers/moderator.js
  server/controllers/productUserCounter.js
  server/controllers/products.js
  server/controllers/users.js
  server/enum/roles.js
  server/error/exceptions.js
  server/models/user.js
  server/package.json
  server/tests/authorization.test.js
  server/tests/kierratysavustin_api.test.js
  server/tests/product_user_counter.test.js
  server/tests/test_helper.js
  server/utils/auth.js
  server/utils/roles.js
Labels: enhancement, Priority Medium

#152 Instruction vote form refactor
  client/src/App.tsx
  client/src/components/RecycleGraph.tsx
  client/src/components/forms/DeleteInstructionForm.tsx
  client/src/components/forms/LoginForm.tsx
  client/src/components/forms/VoteForm.tsx
  client/src/services/productUserCount.ts
  client/src/services/user.ts
  client/src/tests/RecycleStatisticsView.test.tsx
  client/src/tests/Vote.test.js
  client/src/tests/VoteForm.test.tsx
  e2e_tests/cypress/integration/recycling-app.spec.js
  server/controllers/productUserCounter.js
  server/controllers/users.js
  server/requests/dislike_instruction.rest
  server/requests/like_instruction.rest
  server/requests/purchase.rest
  server/requests/recycle.rest
  server/requests/statistics.rest
  server/requests/undislike_instruction.rest
  server/requests/unlike_instruction.rest
  server/requests/user_recycle_rates_per_days.rest
  server/requests/user_recycle_rates_per_product.rest
  server/requests/user_statistics_table.rest
  server/tests/kierratysavustin_api.test.js
  server/tests/test_helper.js
Labels: Priority Medium
